# GitHub Pages configuration
theme: jekyll-theme-minimal
title: Yannish's Homepage
description: Insights into my journey and work in cybersecurity!

author:
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  github           : https://yannkumar.github.io
